name: vigenesia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  persistent_bottom_nav_bar: any
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  pull_to_refresh: ^2.0.0
  get: ^4.6.6
  awesome_select: ^6.0.0
  sticky_headers: ^0.3.0+2
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  auto_route: ^9.2.2
  skeletonizer: ^1.4.2
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  fonts:
    - family: Inter
    - fonts:
      - asset: fonts/Inter-Regular.ttf
      - asset: fonts/Inter-Italic.ttf
        style: italic
      - asset: fonts/Inter-Bold.ttf
        weight: 600
  assets:
    - assets/images/
  uses-material-design: true
